/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mercado;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author marly
 */
public class vista extends javax.swing.JFrame {

    /**
     * Creates new form vista
     */
    public vista() {
        initComponents();
        this.tabladetalles.setModel((TableModel) modelo);
        this.modelo.addColumn("NACIONALIDAD");
        this.modelo.addColumn("GENERO");
        this.modelo.addColumn("TALLA");
        this.modelo.addColumn("PRENDAS");
        this.modelo.addColumn("CANTIDAD");
        this.modelo.addColumn("PRECIO UNITARIO");
        this.modelo.addColumn("TOTAL A PAGAR");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    DefaultTableModel modelo = new DefaultTableModel();
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        qq = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dd = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        nacionalidad = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        generom = new javax.swing.JRadioButton();
        generoh = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        talla = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        prenda = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        precio = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        totalpagar = new javax.swing.JTextField();
        generarcompra = new javax.swing.JButton();
        limpiarA = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabladetalles = new javax.swing.JTable();
        limpiartabla = new javax.swing.JButton();
        quitarcompra = new javax.swing.JButton();
        netopaga = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        netopagaS = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Sistema de tienda");

        jLabel2.setText("NACIONAL");

        jLabel3.setText("Hombre talla: S=0.05, M=0.07, L=0.10");

        jLabel4.setText("Mujer talla: S=0.04, M=0.09, L=0.12");

        jLabel5.setText("EXTRANGEROS");

        jLabel6.setText("Hombre talla: S=0.04, M=0.09, L=0.12 ");

        jLabel7.setText("Mujer talla: S=0.05, M=0.07,L=0.10");

        jLabel8.setText("Nacionalidad");

        nacionalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione ", "Colombiano ", "Extrangero" }));
        nacionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nacionalidadActionPerformed(evt);
            }
        });

        jLabel9.setText("Genero");

        buttonGroup1.add(generom);
        generom.setText("Mujer");
        generom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generomActionPerformed(evt);
            }
        });

        buttonGroup1.add(generoh);
        generoh.setText("Hombre");

        jLabel10.setText("Tallas");

        talla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "S", "M", "L" }));

        jLabel11.setText("Prenda");

        prenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prendaActionPerformed(evt);
            }
        });

        jLabel12.setText("Cantidad");

        cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadActionPerformed(evt);
            }
        });

        jLabel13.setText("Precio");

        jLabel14.setText("Total a pagar");

        generarcompra.setText("Generar compra");
        generarcompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarcompraActionPerformed(evt);
            }
        });

        limpiarA.setText("Limpiar");
        limpiarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ddLayout = new javax.swing.GroupLayout(dd);
        dd.setLayout(ddLayout);
        ddLayout.setHorizontalGroup(
            ddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ddLayout.createSequentialGroup()
                .addGroup(ddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ddLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGroup(ddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ddLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel9))
                            .addGroup(ddLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(generom)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(generoh)))
                        .addGap(18, 18, 18)
                        .addGroup(ddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(talla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(ddLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(generarcompra)
                        .addGap(18, 18, 18)
                        .addComponent(limpiarA, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(ddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ddLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalpagar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ddLayout.createSequentialGroup()
                        .addGroup(ddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prenda, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(ddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        ddLayout.setVerticalGroup(
            ddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ddLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(jLabel13)
                        .addComponent(jLabel12)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(ddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generom)
                    .addComponent(generoh)
                    .addComponent(talla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(totalpagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generarcompra)
                    .addComponent(limpiarA))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout qqLayout = new javax.swing.GroupLayout(qq);
        qq.setLayout(qqLayout);
        qqLayout.setHorizontalGroup(
            qqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qqLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(qqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(dd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        qqLayout.setVerticalGroup(
            qqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qqLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(qqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(qqLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(0, 41, Short.MAX_VALUE))
                    .addComponent(dd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabladetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabladetalles);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
        );

        limpiartabla.setText("Limpiar tabla");
        limpiartabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiartablaActionPerformed(evt);
            }
        });

        quitarcompra.setText("Quitar compra");
        quitarcompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitarcompraActionPerformed(evt);
            }
        });

        netopaga.setText("Neto a pagar");
        netopaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netopagaActionPerformed(evt);
            }
        });

        jLabel15.setText("Neto a pagar S/.");

        netopagaS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netopagaSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(qq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(limpiartabla, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(quitarcompra, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(netopaga, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addGap(39, 39, 39)
                        .addComponent(netopagaS, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(qq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limpiartabla)
                    .addComponent(quitarcompra)
                    .addComponent(netopaga)
                    .addComponent(jLabel15)
                    .addComponent(netopagaS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generomActionPerformed

    private void prendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prendaActionPerformed

    private void cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadActionPerformed
   
    private void netopagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netopagaActionPerformed
    
        double sumatoria;
        double sumatorial=0;
        int totalrow=tabladetalles.getRowCount();
        totalrow-=1;
        for(int i=0; i<= totalrow ; i++){
            sumatoria=Double.parseDouble(String.valueOf(sumatorial));
            sumatorial+=sumatoria;
            
        }
    }//GEN-LAST:event_netopagaActionPerformed

    private void netopagaSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netopagaSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_netopagaSActionPerformed

    private void generarcompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarcompraActionPerformed
        descuentos_hombre_extrangeros();
        descuento_mujer_extrangeras();
        descuento_mujeres_colombianas();
         descuento_hombre_colombiano();
         
         if(generoh.isSelected()){
             this.modelo.addRow(new Object[]{this.nacionalidad.getSelectedIndex(),"Hombre",
                 this.talla.getSelectedItem(),this.prenda.getText(),this.cantidad.getText(),
                 this.precio.getText(),this.totalpagar.getText()});
             
         }
         else if (generom.isSelected()){
             this.modelo.addRow(new Object[]{this.nacionalidad.getSelectedIndex(),"Mujer",
                 this.talla.getSelectedItem(),this.prenda.getText(),this.cantidad.getText(),
                 this.precio.getText(),this.totalpagar.getText()});
             
         }
    }//GEN-LAST:event_generarcompraActionPerformed

    private void limpiarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarAActionPerformed
       this.nacionalidad.setSelectedIndex(0);
       if (generoh.isSelected()){
           
       }
       if (generom.isSelected()){
           
       }
       this.talla.setSelectedIndex(0);
       this.prenda.setText("");
       this.cantidad.setText("");
       this.precio.setText("");
       this.totalpagar.setText("");
    }//GEN-LAST:event_limpiarAActionPerformed

    private void quitarcompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitarcompraActionPerformed
       modelo.removeRow(this.tabladetalles.getSelectedRow());
    }//GEN-LAST:event_quitarcompraActionPerformed

    private void limpiartablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiartablaActionPerformed
      int x= this.modelo.getRowCount();
      for(int y=0; y<=x;y++){
          this.modelo.removeRow(0);
      }
      this.netopaga.setText("");
    }//GEN-LAST:event_limpiartablaActionPerformed

    private void nacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nacionalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nacionalidadActionPerformed

    public void descuentos_hombre_extrangeros() {
        double cantidad_s, precio_s = 0, total_s, desc_s = 0.04;
        double cantidad_m, precio_m, total_m, desc_m = 0.09;
        double cantidad_l, precio_l, total_l, desc_l = 0.12;

        if (nacionalidad.getSelectedIndex() == 2) {
            if (this.generoh.isSelected()) {
                if (talla.getSelectedIndex() == 1) {
                    cantidad_s = Double.parseDouble(this.cantidad.getText());
                    precio_m = Double.parseDouble(this.precio.getText());
                    total_s = (precio_s * cantidad_s) - ((cantidad_s * precio_s) * desc_s);
                    this.totalpagar.setText(String.valueOf(total_s));

                }
            }
        }
        if (nacionalidad.getSelectedIndex() == 2) {
            if (this.generoh.isSelected()) {
                if (talla.getSelectedIndex() == 2) {
                    cantidad_m = Double.parseDouble(this.cantidad.getText());
                    precio_m = Double.parseDouble(this.precio.getText());
                    total_m = (precio_m * cantidad_m) - ((cantidad_m * precio_m) * desc_m);
                    this.totalpagar.setText(String.valueOf(total_m));

                }
            }
        }
        if (nacionalidad.getSelectedIndex() == 2) {
            if (this.generoh.isSelected()) {
                if (talla.getSelectedIndex() == 3) {
                    cantidad_l = Double.parseDouble(this.cantidad.getText());
                    precio_l = Double.parseDouble(this.precio.getText());
                    total_l = (precio_l * cantidad_l) - ((cantidad_l * precio_l) * desc_l);
                    this.totalpagar.setText(String.valueOf(total_l));
                }
            }
        }

    }

    public void descuento_mujer_extrangeras() {
        double cantidad_s, precio_s = 0, total_s, desc_s = 0.05;
        double cantidad_m, precio_m, total_m, desc_m = 0.07;
        double cantidad_l, precio_l, total_l, desc_l = 0.10;

        if (nacionalidad.getSelectedIndex() == 2) {
            if (this.generom.isSelected()) {
                if (talla.getSelectedIndex() == 1) {
                    cantidad_s = Double.parseDouble(this.cantidad.getText());
                    precio_s = Double.parseDouble(this.precio.getText());
                    total_s = (precio_s * cantidad_s) - ((cantidad_s * precio_s) * desc_s);
                    this.totalpagar.setText(String.valueOf(total_s));
                }
            }
        }
        if (nacionalidad.getSelectedIndex() == 2) {
            if (this.generom.isSelected()) {
                if (talla.getSelectedIndex() == 2) {
                    cantidad_m = Double.parseDouble(this.cantidad.getText());
                    precio_m = Double.parseDouble(this.precio.getText());
                    total_m = (precio_m * cantidad_m) - ((cantidad_m * precio_m) * desc_m);
                    this.totalpagar.setText(String.valueOf(total_m));
                }
            }
        }
        if (nacionalidad.getSelectedIndex() == 2) {
            if (this.generom.isSelected()) {
                if (talla.getSelectedIndex() == 3) {
                    cantidad_l = Double.parseDouble(this.cantidad.getText());
                    precio_l = Double.parseDouble(this.precio.getText());
                    total_l = (precio_l * cantidad_l) - ((cantidad_l * precio_l) * desc_l);
                    this.totalpagar.setText(String.valueOf(total_l));
                }
            }
        }

    }

    public void descuento_mujeres_colombianas(){
         double cantidad_s, precio_s = 0, total_s, desc_s = 0.04;
        double cantidad_m, precio_m, total_m, desc_m = 0.09;
        double cantidad_l, precio_l, total_l, desc_l = 0.12;
        
         if (nacionalidad.getSelectedIndex() == 1 ) {
            if (this.generom.isSelected()) {
                if (talla.getSelectedIndex() == 1) {
                    cantidad_s = Double.parseDouble(this.cantidad.getText());
                    precio_s = Double.parseDouble(this.precio.getText());
                    total_s= (precio_s * cantidad_s) - ((cantidad_s * precio_s) * desc_s);
                    this.totalpagar.setText(String.valueOf(total_s));
                }
            }
         }
         
         
          if (nacionalidad.getSelectedIndex() == 1 ) {
            if (this.generom.isSelected()) {
                if (talla.getSelectedIndex() == 2) {
                    cantidad_m = Double.parseDouble(this.cantidad.getText());
                    precio_m = Double.parseDouble(this.precio.getText());
                    total_m= (precio_m* cantidad_m) - ((cantidad_m * precio_m) * desc_m);
                    this.totalpagar.setText(String.valueOf(total_m));
                }
            }
          }
           if (nacionalidad.getSelectedIndex() == 1 ) {
            if (this.generom.isSelected()) {
                if (talla.getSelectedIndex() == 3) {
                    cantidad_l = Double.parseDouble(this.cantidad.getText());
                    precio_l = Double.parseDouble(this.precio.getText());
                    total_l= (precio_l* cantidad_l) - ((cantidad_l * precio_l) * desc_l);
                    this.totalpagar.setText(String.valueOf(total_l));
                }
            }
           }
           
           
    }
    public void descuento_hombre_colombiano(){
         double cantidad_s, precio_s = 0, total_s, desc_s = 0.05;
        double cantidad_m, precio_m, total_m, desc_m = 0.07;
        double cantidad_l, precio_l, total_l, desc_l = 0.10;
        
        
         if (nacionalidad.getSelectedIndex() == 1 ) {
            if (this.generoh.isSelected()) {
                if (talla.getSelectedIndex() == 1) {
                    cantidad_s = Double.parseDouble(this.cantidad.getText());
                    precio_s = Double.parseDouble(this.precio.getText());
                    total_s= (precio_s * cantidad_s) - ((cantidad_s * precio_s) * desc_s);
                    this.totalpagar.setText(String.valueOf(total_s));
                }
            }
         }
         
         
          if (nacionalidad.getSelectedIndex() == 1 ) {
            if (this.generoh.isSelected()) {
                if (talla.getSelectedIndex() == 2) {
                    cantidad_m = Double.parseDouble(this.cantidad.getText());
                    precio_m = Double.parseDouble(this.precio.getText());
                    total_m= (precio_m* cantidad_m) - ((cantidad_m * precio_m) * desc_m);
                    this.totalpagar.setText(String.valueOf(total_m));
                }
            }
          }
           if (nacionalidad.getSelectedIndex() == 1 ) {
            if (this.generoh.isSelected()) {
                if (talla.getSelectedIndex() == 3) {
                    cantidad_l = Double.parseDouble(this.cantidad.getText());
                    precio_l = Double.parseDouble(this.precio.getText());
                    total_l= (precio_l* cantidad_l) - ((cantidad_l * precio_l) * desc_l);
                    this.totalpagar.setText(String.valueOf(total_l));
                }
            }
           }
           
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cantidad;
    private javax.swing.JPanel dd;
    private javax.swing.JButton generarcompra;
    private javax.swing.JRadioButton generoh;
    private javax.swing.JRadioButton generom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton limpiarA;
    private javax.swing.JButton limpiartabla;
    private javax.swing.JComboBox<String> nacionalidad;
    private javax.swing.JButton netopaga;
    private javax.swing.JTextField netopagaS;
    private javax.swing.JTextField precio;
    private javax.swing.JTextField prenda;
    private javax.swing.JPanel qq;
    private javax.swing.JButton quitarcompra;
    private javax.swing.JTable tabladetalles;
    private javax.swing.JComboBox<String> talla;
    private javax.swing.JTextField totalpagar;
    // End of variables declaration//GEN-END:variables
}
